---
- name: Include register with RHSM
  when: lb1136_rhel10_hol_use_rhsm_for_node2 | bool
  ansible.builtin.include_tasks:
    file: rhsm.yml

- name: Include lab config
  ansible.builtin.include_tasks:
    file: lab-config.yml

- name: Include letsencrypt certificate for node3
  when: lb1136_rhel10_hol_lecertificate_for_node3 | bool
  ansible.builtin.include_tasks:
    file: lecertificate.yml
