---

- ansible.builtin.debug:
    msg: "## BEGIN SETUP ROLE for: The Definitive RHEL10 Hands-On Lab"

##
##    Every host touched by the role should create a progress log
##

- name: "rhel10_setup - create progress log"
  ansible.builtin.lineinfile:
    state: present
    create: true
    insertafter: EOF
    dest: "/var/tmp/lb1136-progress.log"
    line: "lb1136_rhel10_hol role processing started"

# Every host in group 'nodes'
- block:

    - name: "rhel10_setup - working on group 'nodes'"
      lineinfile:
        state: present
        create: true
        insertafter: EOF
        dest: "/var/tmp/lb1136-progress.log"
        line: "working on node1"

    - name: rhel10_setup - create student user
      ansible.builtin.user:
        name: "{{ student_name }}"
        state: present
        shell: /bin/bash
        password: "{{ common_password | password_hash }}"
      
    - name: rhel10_setup - install minimum package requirements
      ansible.builtin.package: 
        name: ansible-core,rhel-system-roles,tmux,git 
        state: installed

  when: inventory_hostname in groups['nodes']

  
# Only 'node1'
- block:
  - name: "rhel10_setup - working on 'node1'"
    lineinfile:
        state: present
        create: true
        insertafter: EOF
        dest: "/var/tmp/lb1136-progress.log"
        line: "working on node1"
        
  ignore_errors: yes
  become: true
  when: 
    - inventory_hostname in groups['nodes']
    - inventory_hostname_short == 'node1'

#  - name: git clone course repo to node1
#    ansible.builtin.git:
#      repo: "https://github.com/xtophd/RHEL10-Workshop.git"
#      dest: "/root/RHEL10-Workshop"
#      version: "summit-2025"
#      clone: yes
  
#  - name: Create gpte-guid config file
#    copy:
#      dest: "/root/RHEL10-Workshop/config/gpte-guid.txt"
#      mode: "400"
#      content: "{{ guid }}"
  
#  - name: Create gpte-studentpw config file
#    copy:
#      dest: "/root/RHEL10-Workshop/config/gpte-studentpw.txt"
#      mode: "400"
#      content: "{{ student_password }}"
    
#  - name: Create gpte-pub-fqdn-shortname config files
#    vars:
#      shortname: "{{ item | regex_replace('\\..*$') }}"
#      hostname: "{{ item | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
#    copy:
#      dest: "/root/RHEL10-Workshop/config/gpte-pub-fqdn-{{ shortname }}.txt"
#      mode: "400"
#      content: "{{ hostname }}"
#    with_items:
#      - "{{ groups['bastions'][0] }}"
#      - "{{ groups['nodes'] }}"


