---
- block:
  - name: Create the user on nodes
    when: inventory_hostname in groups['nodes']
    ansible.builtin.user:
      name: "{{ student_name }}"
      state: present
      shell: /bin/bash
      password: "{{ common_password | password_hash }}"

  - name: git clone course repo to node1
    ansible.builtin.git:
      repo: "https://github.com/xtophd/RHEL10-Workshop.git"
      dest: "/root/RHEL10-Workshop"
      version: "summit-2025"
      clone: yes
    when: 
      - inventory_hostname in groups['nodes']
      - inventory_hostname_short == 'node1'
    ignore_errors: yes
 
  become: true

