---

# Every host been touched by the role should create a progress log
- name: Create file to log setup progress
  ansible.builtin.copy:
    dest: "/var/tmp/lb1136-progress.log"
    content: |
        lb1136_rhel10_hol role processing started
        {{ ansible_hostname }}

# Every host in group 'nodes'
- block:
  - name: Create the user on nodes
    when: inventory_hostname in groups['nodes']
    ansible.builtin.user:
      name: "{{ student_name }}"
      state: present
      shell: /bin/bash
      password: "{{ common_password | password_hash }}"

# Host in group 'nodes' and hostname equals 'node1'
#   don't allow errors to block deployment
- block:
  - name: "rhel9-prep : TEMPLATE /etc/motd (incomplete)"
    ansible.builtin.template:
      src: motd-incomplete.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644

  ignore_errors: yes
  become: true
  when: 
    - inventory_hostname in groups['nodes']
    - inventory_hostname_short == 'node1'


#  - name: Install minimal packages
#    package: 
#      name: ansible-core,rhel-system-roles,tmux,git 
#      state: installed

#  - name: git clone course repo to node1
#    ansible.builtin.git:
#      repo: "https://github.com/xtophd/RHEL10-Workshop.git"
#      dest: "/root/RHEL10-Workshop"
#      version: "summit-2025"
#      clone: yes
  
#  - name: Create gpte-guid config file
#    copy:
#      dest: "/root/RHEL10-Workshop/config/gpte-guid.txt"
#      mode: "400"
#      content: "{{ guid }}"
  
#  - name: Create gpte-studentpw config file
#    copy:
#      dest: "/root/RHEL10-Workshop/config/gpte-studentpw.txt"
#      mode: "400"
#      content: "{{ student_password }}"
    
#  - name: Create gpte-pub-fqdn-shortname config files
#    vars:
#      shortname: "{{ item | regex_replace('\\..*$') }}"
#      hostname: "{{ item | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
#    copy:
#      dest: "/root/RHEL10-Workshop/config/gpte-pub-fqdn-{{ shortname }}.txt"
#      mode: "400"
#      content: "{{ hostname }}"
#    with_items:
#      - "{{ groups['bastions'][0] }}"
#      - "{{ groups['nodes'] }}"


