---

- ansible.builtin.debug:
    msg: "## rhel10_setup - start role lb1136_rhel10_hol 'The Definitive RHEL10 Hands-On Lab'"

##
##    Every host touched by the role should create a progress log
##

- name: "rhel10_setup - create progress log"
  ansible.builtin.lineinfile:
    state: present
    create: true
    insertafter: EOF
    dest: "/var/tmp/lb1136-progress.log"
    line: "[{{ ansible_hostname }}] lb1136_rhel10_hol role processing"

- block:

    - name: "rhel10_setup - working on hostgroup 'nodes'"
      lineinfile:
        state: present
        create: true
        insertafter: EOF
        dest: "/var/tmp/lb1136-progress.log"
        line: "[{{ ansible_hostname }}] working on hostgroup 'nodes' which includes {{ groups.nodes }}"

    - name: rhel10_setup - create student user
      ansible.builtin.user:
        name: "{{ student_name }}"
        state: present
        shell: /bin/bash
        password: "{{ common_password | password_hash }}"
      
  when: 
    - inventory_hostname in groups['nodes']

# Every host in group 'nodes' except 'leapp'
- block:

    - name: "rhel10_setup - working on hostgroup 'nodes' except 'leapp'"
      lineinfile:
        state: present
        create: true
        insertafter: EOF
        dest: "/var/tmp/lb1136-progress.log"
        line: "[{{ ansible_hostname }}] working on group nodes except leapp"
      
    - name: rhel10_setup - install minimum package requirements
      ansible.builtin.package: 
        name: ansible-core,rhel-system-roles,tmux,git,bind-utils 
        state: installed

  when: 
    - inventory_hostname in groups['nodes']
    - inventory_hostname_short != 'leapp'

# Only 'node1'
- block:
  - name: "rhel10_setup - working only on node 'node1'"
    lineinfile:
        state: present
        create: true
        insertafter: EOF
        dest: "/var/tmp/lb1136-progress.log"
        line: "[{{ ansible_hostname }}] working only on node1"

  - name: "rhel10-setup - dumping hostvars"
    copy:
      destination: "/var/tmp/ll1136-hostvars.yml"
      content: "{{ hostvars | to_nice_yml }}"
        
  - name: "rhel10-setup - git clone course repo"
    ansible.builtin.git:
      repo: "https://github.com/xtophd/RHEL10-Workshop.git"
      dest: "/root/RHEL10-Workshop"
      version: "summit-2025"
      clone: yes

  - name: "rhel10-setup - create gpte-guid config file"
    ansible.builtin.copy:
      dest: "/root/RHEL10-Workshop/config/gpte-guid.txt"
      mode: "400"
      content: "{{ guid }}"

  - name: "rhel10-setup - create gpte-student config file"
    ansible.builtin.copy:
      dest: "/root/RHEL10-Workshop/config/gpte-student.txt"
      mode: "400"
      content: "{{ student_name }}"

  - name: "rhel10-setup - create gpte-studentpw config file"
    ansible.builtin.copy:
      dest: "/root/RHEL10-Workshop/config/gpte-studentpw.txt"
      mode: "400"
      content: "{{ student_password }}"

  - name: "rhel10-setup - create gpte-subdomain-internal config file"
    ansible.builtin.copy:
      dest: "/root/RHEL10-Workshop/config/gpte-subdomain-internal.txt"
      mode: "400"
      content: "{{ subdomain_internal }}"
          
  - name: "rhel10-setup - create gpte-pub-fqdn-shortname config files"
    vars:
      shortname: "{{ item | regex_replace('\\..*$') }}"
      hostname: "{{ item | regex_replace('\\..*$') }}.{{ guid }}{{ subdomain_base_suffix }}"
    ansible.builtin.copy:
      dest: "/root/RHEL10-Workshop/config/gpte-pub-fqdn-{{ shortname }}.txt"
      mode: "400"
      content: "{{ hostname }}"
    with_items:
      - "{{ groups['nodes'] }}"
#      - "{{ groups['bastions'][0] }}"
        
  ignore_errors: yes
  become: true
  when: 
    - inventory_hostname in groups['nodes']
    - inventory_hostname_short == 'node1'

  


