---
- name: Register node2 with specific activationkeys
  when: 
    - inventory_hostname in groups['isolated']
    - inventory_hostname_short == 'node2'
  block: 
    - name: Unregister From Subscription Manager
      ansible.builtin.command: subscription-manager unregister
      register: r_unregister
      failed_when: >-
        r_unregister is failed and
        r_unregister.stderr | default('') != 'This system is currently not registered.'
      ignore_errors: true

    - name: Remove satellite Cert
      ansible.builtin.package:
        name: katello-ca-consumer-*.noarch
        state: absent
        disablerepo: "*"
      ignore_errors: true

    - name: Update CA Trust Bundle
      ansible.builtin.command: update-ca-trust

    - name: Find current repository files
      ansible.builtin.find:
        paths: /etc/yum.repos.d
        recurse: no
        patterns:
        - '*.repo'
      register: r_find_repos

    - name: Remove current repository files
      ansible.builtin.file:
        path: "{{ file.path }}"
        state: absent
      loop: "{{ r_find_repos.files }}"
      loop_control:
        loop_var: file
        label: "{{ file.path }}"

    - name: Restore rhsm.conf
      ansible.builtin.copy:
        src: /etc/rhsm/rhsm.conf.cloud_save
        dest: /etc/rhsm/rhsm.conf
        remote_src: true
        mode: "0644"

    - name: Remove katello facts files
      ansible.builtin.file:
        path: "/etc/rhsm/facts/katello.facts"
        state: absent

    - name: Register Node to RHSM
      ansible.builtin.shell: >-
        subscription-manager config --rhsm.manage_repos=1

    - name: Register Node to RHSM
      ansible.builtin.shell: >-
        subscription-manager register
        --org "{{ lb1136_rhel10_hol_sat_org }}"
        --activationkey "{{ lb1136_rhel10_hol_sat_activation_key }}"
